version: '3.9'

services:
  db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_DB=dbTransport
      - POSTGRES_USER=dbApp
      - POSTGRES_PASSWORD=qwer4321

    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
