INSERT INTO seguridad.tipo_identificacion VALUES (0, 'No definido');
INSERT INTO seguridad.tipo_identificacion VALUES (10, 'Cédula de ciudadanía');
INSERT INTO seguridad.rol VALUES (0, 'No definido');
INSERT INTO seguridad.rol VALUES (10, 'Administrador');
INSERT INTO seguridad.rol VALUES (20, 'Solicitante');
INSERT INTO seguridad.rol VALUES (30, 'Conductor');
INSERT INTO seguridad.rol VALUES (40, 'Agente');
INSERT INTO seguridad.usuario VALUES (0, 0, 0, 'No definido', 'No definido', 'No definido', 'No definido', 'No definido');
INSERT INTO transporte.tipo_vehiculo VALUES (0, 'No definido', 0);
INSERT INTO transporte.tipo_vehiculo VALUES (10, 'Automóvil', 2);
INSERT INTO transporte.tipo_vehiculo VALUES (20, 'Campero', 2);
INSERT INTO transporte.tipo_vehiculo VALUES (30, 'Camioneta', 2);
INSERT INTO transporte.tipo_vehiculo VALUES (40, 'Microbus', 3);
INSERT INTO transporte.conductor VALUES (0, 0, 'No definido');
INSERT INTO transporte.vehiculo VALUES (0, 0, 0, 'No definido', 'No definido', 'No definido', 0, false);
INSERT INTO transporte.solicitante VALUES (0, 0, 0, 0);
INSERT INTO transporte.viaje VALUES (0, 0, 0, 0, 0, 0, 0, 0, 'No definido');
INSERT INTO pago.medio_pago VALUES (0, 'No definido', 'No definido');
INSERT INTO pago.medio_pago VALUES (10, 'Tarjeta de crédito', 'Visa');
INSERT INTO pago.medio_pago VALUES (20, 'Tarjeta de crédito', 'MasterCard');
INSERT INTO pago.medio_pago VALUES (30, 'Efectivo', 'Efectivo');
INSERT INTO pago.promocion VALUES (0, 0, 'Efectivo', false);
INSERT INTO pago.pago VALUES (0, 0, 0, 0, 0, 0, 0);
INSERT INTO pago.referido VALUES (0, 0, 'No definido', 'No definido');
INSERT INTO soporte.agente VALUES (0, 0, 'No definido');
INSERT INTO soporte.pqrs VALUES (0, 0, 'N', 'No definido', 'No definido');